// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entities "domain-driven-design-layout/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// AddressRepositoryMock is an autogenerated mock type for the AddressRepositoryMock type
type AddressRepositoryMock struct {
	mock.Mock
}

// CreateAddress provides a mock function with given fields: ctx, userID, addressPrototype
func (_m *AddressRepositoryMock) CreateAddress(ctx entities.ApplicationContext, userID int64, addressPrototype entities.AddressPrototype) (entities.Address, error) {
	ret := _m.Called(ctx, userID, addressPrototype)

	var r0 entities.Address
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64, entities.AddressPrototype) entities.Address); ok {
		r0 = rf(ctx, userID, addressPrototype)
	} else {
		r0 = ret.Get(0).(entities.Address)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, int64, entities.AddressPrototype) error); ok {
		r1 = rf(ctx, userID, addressPrototype)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAddress provides a mock function with given fields: ctx, addressID
func (_m *AddressRepositoryMock) DeleteAddress(ctx entities.ApplicationContext, addressID int64) error {
	ret := _m.Called(ctx, addressID)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) error); ok {
		r0 = rf(ctx, addressID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserAddresses provides a mock function with given fields: ctx, userID
func (_m *AddressRepositoryMock) DeleteUserAddresses(ctx entities.ApplicationContext, userID int64) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddress provides a mock function with given fields: ctx, addressID
func (_m *AddressRepositoryMock) GetAddress(ctx entities.ApplicationContext, addressID int64) (*entities.Address, error) {
	ret := _m.Called(ctx, addressID)

	var r0 *entities.Address
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) *entities.Address); ok {
		r0 = rf(ctx, addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, int64) error); ok {
		r1 = rf(ctx, addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
