// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entities "domain-driven-design-layout/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// DeleteUserMock is an autogenerated mock type for the DeleteUserMock type
type DeleteUserMock struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, userID
func (_m *DeleteUserMock) Execute(ctx entities.ApplicationContext, userID int64) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
