// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entities "domain-driven-design-layout/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// FindUsersByIdListMock is an autogenerated mock type for the FindUsersByIdListMock type
type FindUsersByIdListMock struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, userIDs
func (_m *FindUsersByIdListMock) Execute(ctx entities.ApplicationContext, userIDs []int64) ([]entities.User, error) {
	ret := _m.Called(ctx, userIDs)

	var r0 []entities.User
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, []int64) []entities.User); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, []int64) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
