// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entities "domain-driven-design-layout/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MainDatabaseMock is an autogenerated mock type for the MainDatabaseMock type
type MainDatabaseMock struct {
	mock.Mock
}

// CommitTx provides a mock function with given fields:
func (_m *MainDatabaseMock) CommitTx() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAddress provides a mock function with given fields: ctx, userID, addressPrototype
func (_m *MainDatabaseMock) CreateAddress(ctx entities.ApplicationContext, userID int64, addressPrototype entities.AddressPrototype) (entities.Address, error) {
	ret := _m.Called(ctx, userID, addressPrototype)

	var r0 entities.Address
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64, entities.AddressPrototype) entities.Address); ok {
		r0 = rf(ctx, userID, addressPrototype)
	} else {
		r0 = ret.Get(0).(entities.Address)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, int64, entities.AddressPrototype) error); ok {
		r1 = rf(ctx, userID, addressPrototype)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, userPrototype
func (_m *MainDatabaseMock) CreateUser(ctx entities.ApplicationContext, userPrototype entities.UserPrototype) (entities.User, error) {
	ret := _m.Called(ctx, userPrototype)

	var r0 entities.User
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, entities.UserPrototype) entities.User); ok {
		r0 = rf(ctx, userPrototype)
	} else {
		r0 = ret.Get(0).(entities.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, entities.UserPrototype) error); ok {
		r1 = rf(ctx, userPrototype)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAddress provides a mock function with given fields: ctx, addressID
func (_m *MainDatabaseMock) DeleteAddress(ctx entities.ApplicationContext, addressID int64) error {
	ret := _m.Called(ctx, addressID)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) error); ok {
		r0 = rf(ctx, addressID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *MainDatabaseMock) DeleteUser(ctx entities.ApplicationContext, userID int64) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserAddresses provides a mock function with given fields: ctx, userID
func (_m *MainDatabaseMock) DeleteUserAddresses(ctx entities.ApplicationContext, userID int64) error {
	ret := _m.Called(ctx, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAddress provides a mock function with given fields: ctx, addressID
func (_m *MainDatabaseMock) GetAddress(ctx entities.ApplicationContext, addressID int64) (*entities.Address, error) {
	ret := _m.Called(ctx, addressID)

	var r0 *entities.Address
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) *entities.Address); ok {
		r0 = rf(ctx, addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, int64) error); ok {
		r1 = rf(ctx, addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *MainDatabaseMock) GetUser(ctx entities.ApplicationContext, userID int64) (*entities.User, error) {
	ret := _m.Called(ctx, userID)

	var r0 *entities.User
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, int64) *entities.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, userIDs
func (_m *MainDatabaseMock) GetUsers(ctx entities.ApplicationContext, userIDs []int64) ([]entities.User, error) {
	ret := _m.Called(ctx, userIDs)

	var r0 []entities.User
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, []int64) []entities.User); ok {
		r0 = rf(ctx, userIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, []int64) error); ok {
		r1 = rf(ctx, userIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollbackTx provides a mock function with given fields:
func (_m *MainDatabaseMock) RollbackTx() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *MainDatabaseMock) UpdateUser(ctx entities.ApplicationContext, user entities.User) (entities.User, error) {
	ret := _m.Called(ctx, user)

	var r0 entities.User
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, entities.User) entities.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(entities.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, entities.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
