// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entities "domain-driven-design-layout/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// UpdateUserMock is an autogenerated mock type for the UpdateUserMock type
type UpdateUserMock struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, user
func (_m *UpdateUserMock) Execute(ctx entities.ApplicationContext, user entities.User) (entities.User, error) {
	ret := _m.Called(ctx, user)

	var r0 entities.User
	if rf, ok := ret.Get(0).(func(entities.ApplicationContext, entities.User) entities.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(entities.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(entities.ApplicationContext, entities.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
