version: "2.1"
services:
  ddd-layout-app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - env.test
    depends_on:
      - ddd-layout-postgres
  ddd-layout-postgres:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users-db
  prometheus-server:
    image: prom/prometheus:v2.32.1
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
volumes:
  pgdata: